config/routes.rb
Rails.application.routes.draw do


  resources :score_types
  #, :conditions => { :method => :get }
  match "/documents/:model/:folder/:id/:basename.:extension" => "redocuments#download", via: :get

  resources :award_options
  resources :nomination_types

  devise_scope :user do
     delete '/users/sign_out' => 'devise/sessions#destroy'
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'landing#index'
  devise_for :users
  resources :users

  # You can have the root of your site routed with "root"
  #root to: 'dashboards#dashboard_1'
  get '/nojswarning', to: "landing#nojavascript"
  get 'packards/confirmation', to: "packards#confirmation"
  get 'shoulds/confirmation', to: "shoulds#confirmation"
  get 'developments/confirmation', to: "developments#confirmation"
  get 'achievements/confirmation', to: "achievements#confirmation"
  get 'product_supports/confirmation', to: "product_supports#confirmation"
  get 'logistics/confirmation', to: "logistics#confirmation"

  get 'boards/expired', to: "boards#expired"
  get 'nominations/expired', to: "nominations#expired"
  get 'nominations/update_awards', as: 'update_awards'
  get 'nominations/list', to: "nominations#list"
  get 'boards/list', to: "boards#list"
  get 'asps/confirmation', to: "asps#confirmation"
  get 'battalions/confirmation', to: "battalions#confirmation"
  get 'bops/confirmation', to: "bops#confirmation"
  get 'brigades/confirmation', to: "brigades#confirmation"
  get 'cps/confirmation', to: "cps#confirmation"
  get 'decps/confirmation', to: "decps#confirmation"
  get 'esis/confirmation', to: "esis#confirmation"
  get 'loys/confirmation', to: "loys#confirmation"
  get 'ncos/confirmation', to: "ncos#confirmation"
  get 'pmpdo05s/confirmation', to: "pmpdo05s#confirmation"
  get 'pmpdo06s/confirmation', to: "pmpdo06s#confirmation"
  get 'pmpdp05s/confirmation', to: "pmpdp05s#confirmation"
  get 'pmpdp06s/confirmation', to: "pmpdp06s#confirmation"
  get 'stps/confirmation', to: "stps#confirmation"
  get 'saec_teams/confirmation', to: "saec_teams#confirmation"
  get 'saec_specs/confirmation', to: "saec_specs#confirmation"
  get 'saec_offs/confirmation', to: "saec_offs#confirmation"
  get 'flexs/confirmation', to: "flexs#confirmation"
  
  get 'scores/score_print', to: "scores#score_print"
  get 'scores/reports', to: "scores#reports"
  get 'scores/:id/score_report', to: "scores#score_report"
  get 'scores/:id/score_print', to: "scores#score_print"

  resources :nominations
  resources :packards  #, controller: 'nominations', type: 'Packard'
  resources :shoulds
  resources :developments
  resources :achievements
  resources :product_supports
  resources :logistics
  resources :boards
  resources :scores
  resources :asps
  resources :battalions
  resources :bops
  resources :brigades
  resources :cps
  resources :decps
  resources :esis
  resources :loys
  resources :ncos
  resources :pmpdo05s
  resources :pmpdo06s
  resources :pmpdp05s
  resources :pmpdp06s
  resources :stps
  resources :flexs
  resources :saec_teams
  resources :saec_specs
  resources :saec_offs
  resources :score_types

  get "settings" => "settings#set"
  post "settings" => "settings#update"

  #get 'sites/:name', :to => 'sites#show', :as => site
  #devise_for :members do get '/members/sign_out' => 'devise/sessions#destroy' end



  get "landing/version"
  get "landing/index"
  get "landing/nomination"



  get "*any", via: :all, to: "errors#not_found"

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
 
  end

  def nomination
    render :layout => "nomination"
  end

  def version
    render :layout => "empty"
  end

  def nojavascript

  end

end

app/views/landing/index.html.erb
<%= render "shared/usaasc_head" %>

<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <p id="notice"><%= notice %></p>
    </div>
</div>

<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">
          <div class="ibox-title">
              <h4>Menu Options</h4>
          </div>
          <div class="ibox-content">
            <% if current_user.nil? %>
            <ul>
              <li><%= link_to 'View Nomination Forms', :controller => "nominations", :action => "list" %></li>
            </ul>
            <% end %>

            <% if not current_user.nil? %>
            <% if current_user.admin? %>
            <ul>
              <li><%= link_to 'View Nomination Forms', :controller => "nominations", :action => "list" %></li>
            </ul>
            <ul>
              <li><%= link_to 'Manage Nomination Types', nomination_types_path %></li>
            </ul>
            <ul>
              <li><%= link_to 'Manage Award Options', award_options_path %></li>
            </ul>

            <ul>
              <li><%= link_to 'Manage Score Types', :controller => "score_types", :action => "index" %></li>
            </ul>
            <ul>
              <li><%= link_to 'Manage Boards', :controller => "boards", :action => "index" %></li>
            </ul>
            <ul>
              <li><%= link_to 'Manage Users', :controller => "users", :action => "index" %></li>
            </ul>
            <ul>
              <li><%= link_to 'Manage Nominations', :controller => "nominations", :action => "index" %></li>
            </ul>
            <ul>
              <li><%= link_to 'Score Reports', :controller => "scores", :action => "reports" %></li>
            </ul>
            <ul>
              <li><%= link_to 'Set Award Year', :controller => "settings", :action => "set" %></li>
            </ul>
            <% end %>
            <% if current_user.admin? || current_user.judge? %>
            <ul>
              <li><%= link_to 'View Boards', :controller => "boards", :action => "list" %></li>
            </ul>
            <% end %>
            <% end %>
          </div>
        </div>
    </div>
</div>

app/views/landing/nojavascript.html.erb
<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">

            <div class="ibox-content">
<h4>In order to use this site, you need to enable javascript.</h4>

</div>
</div>
</div>
</div>

app/views/landing/version.html.erb
Readme
<br/>
<br/>
1.4 - 05/17/2016
<br/>
<ul>
  <li>add more search criteria on manage nominations<li>
</ul>    
1.3 - 05/16/2016
<br/>
<ul>
  <li>modify user page to create password</li>
  <li>assign user (role judge) to score a nomination type</li>
</ul>
<br/>
1.2 - 05/15/2016
<ul>
  <li>remove sign-in from nomination forms page </li>
  <li>change devise_helper message</li>
</ul>
<br/>
1.1
<br/>
1.0