config/routes.rb
Rails.application.routes.draw do


  resources :score_types
  #, :conditions => { :method => :get }
  match "/documents/:model/:folder/:id/:basename.:extension" => "redocuments#download", via: :get

  resources :award_options
  resources :nomination_types

  devise_scope :user do
     delete '/users/sign_out' => 'devise/sessions#destroy'
     get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root to: 'landing#index'
  devise_for :users
  resources :users

  # You can have the root of your site routed with "root"
  #root to: 'dashboards#dashboard_1'
  get '/nojswarning', to: "landing#nojavascript"
  get 'packards/confirmation', to: "packards#confirmation"
  get 'shoulds/confirmation', to: "shoulds#confirmation"
  get 'developments/confirmation', to: "developments#confirmation"
  get 'achievements/confirmation', to: "achievements#confirmation"
  get 'product_supports/confirmation', to: "product_supports#confirmation"
  get 'logistics/confirmation', to: "logistics#confirmation"

  get 'boards/expired', to: "boards#expired"
  get 'nominations/expired', to: "nominations#expired"
  get 'nominations/update_awards', as: 'update_awards'
  get 'nominations/list', to: "nominations#list"
  get 'boards/list', to: "boards#list"
  get 'asps/confirmation', to: "asps#confirmation"
  get 'battalions/confirmation', to: "battalions#confirmation"
  get 'bops/confirmation', to: "bops#confirmation"
  get 'brigades/confirmation', to: "brigades#confirmation"
  get 'cps/confirmation', to: "cps#confirmation"
  get 'decps/confirmation', to: "decps#confirmation"
  get 'esis/confirmation', to: "esis#confirmation"
  get 'loys/confirmation', to: "loys#confirmation"
  get 'ncos/confirmation', to: "ncos#confirmation"
  get 'pmpdo05s/confirmation', to: "pmpdo05s#confirmation"
  get 'pmpdo06s/confirmation', to: "pmpdo06s#confirmation"
  get 'pmpdp05s/confirmation', to: "pmpdp05s#confirmation"
  get 'pmpdp06s/confirmation', to: "pmpdp06s#confirmation"
  get 'stps/confirmation', to: "stps#confirmation"
  get 'saec_teams/confirmation', to: "saec_teams#confirmation"
  get 'saec_specs/confirmation', to: "saec_specs#confirmation"
  get 'saec_offs/confirmation', to: "saec_offs#confirmation"
  get 'flexs/confirmation', to: "flexs#confirmation"
  
  get 'scores/score_print', to: "scores#score_print"
  get 'scores/reports', to: "scores#reports"
  get 'scores/:id/score_report', to: "scores#score_report"
  get 'scores/:id/score_print', to: "scores#score_print"

  resources :nominations
  resources :packards  #, controller: 'nominations', type: 'Packard'
  resources :shoulds
  resources :developments
  resources :achievements
  resources :product_supports
  resources :logistics
  resources :boards
  resources :scores
  resources :asps
  resources :battalions
  resources :bops
  resources :brigades
  resources :cps
  resources :decps
  resources :esis
  resources :loys
  resources :ncos
  resources :pmpdo05s
  resources :pmpdo06s
  resources :pmpdp05s
  resources :pmpdp06s
  resources :stps
  resources :flexs
  resources :saec_teams
  resources :saec_specs
  resources :saec_offs
  resources :score_types

  get "settings" => "settings#set"
  post "settings" => "settings#update"

  #get 'sites/:name', :to => 'sites#show', :as => site
  #devise_for :members do get '/members/sign_out' => 'devise/sessions#destroy' end



  get "landing/version"
  get "landing/index"
  get "landing/nomination"



  get "*any", via: :all, to: "errors#not_found"

end

app/models/nomination.rb
require 'valid_email'
class Nomination < ActiveRecord::Base
  mount_uploader :endorsement_letter, EndorsementLetterUploader
  mount_uploader :submission_form_award_narrative, SubmissionFormAwardNarrativeUploader
  mount_uploader :nominee_organization_logo, NomineeOrganizationLogoUploader
  mount_uploader :submission_word_document, SubmissionWordDocumentUploader
  mount_uploader :submission_pdf, SubmissionPdfUploader
  mount_uploader :submission_packet, SubmissionPacketUploader
  mount_uploader :nominee_photograph_one, NomineePhotographOneUploader
  mount_uploader :nominee_photograph_two, NomineePhotographTwoUploader
  mount_uploader :additional_supporting_graphics, AdditionalSupportingGraphicsUploader
  mount_uploader :monetary_awd, MonetaryAwdUploader

  belongs_to :nomination_type
  belongs_to :award_option

  validates :unit_commander_first_name, :unit_commander_last_name,  :unit_commander_phone,:unit_commander_email, :unit_commander_organization, :presence => true
  validates :nominating_point_of_contact_first_name, :nominating_point_of_contact_last_name, :nominating_point_of_contact_email,
            :nominating_point_of_contact_phone, :nominating_point_of_contact_organization_address_1, :nominating_point_of_contact_city,
              :presence => true
  validates :award_option_id, :presence => true
  validates :nominee_email, :email => true, :presence => true
  validates :nominee_organization, :nominee_command,
              :presence => true






  #validates :photo_a, :presence => true
  validates :nominating_point_of_contact_email, :presence => true, :email => true

  enum status: [:entered, :approved, :scored, :deleted]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :entered
  end

  def self.nomination_types
    %w(Packard Should Achievement Development ProductSupport Logistic Asp Battalion Bop Brigade Cp Decp Esi Loy Nco Pmpdo05 Pmpdo06 Pmpdp05 Pmpdp06 Stp SaecTeam SaecOff SaecSpec)
  end

  #def self.name_search
  #  :nominee_last_name + :nominee_first_name
  #end

  #paginates_per 1000

  # note singular "validate" for custom function
  validate :nominee_name_or_team_name

  attr_reader :name

  def name
    if (nominee_first_name.blank? && nominee_last_name.blank?)
      nominee_team_name
    else
      nominee_first_name + " " + nominee_last_name
    end
  end

  private

  def nominee_name_or_team_name
    if (nominee_first_name.blank? && nominee_last_name.blank? && nominee_team_name.blank?)
      errors.add(:base, 'Nominee Name or Nominee Team Name must be entered')
    end
  end


end

app/models/nomination_type.rb
class NominationType < ActiveRecord::Base
  mount_uploader :awards_announcement, AwardsAnnouncementUploader
  mount_uploader :implementing_instructions, ImplementingInstructionsUploader
  mount_uploader :submission_form, SubmissionFormUploader
  mount_uploader :award_narrative, AwardNarrativeUploader
  mount_uploader :guidelines, GuidelinesUploader
  has_many :award_options
  has_many :nominations
  serialize :award_years_list
end

app/controllers/nominations_controller.rb
class NominationsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :update, :edit]
  before_action :set_nomination, only: [:show, :edit, :update, :destroy]
  before_action :set_nomination_type
  before_action :manager_or_admin_only, :except => [:list, :expired]

  include DocumentService

  def expired
  end

  # GET /boats
  # GET /boats.json
  def index
    #ßparams[:nomination_nomination_year] ||= Settings.current_year
    @nominations = Nomination.all
    if params[:status].nil?
      params[:status] = ["0","1","2"]
    end
    @statuses = [:entered, :approved, :scored, :deleted]

    if params[:nomination_nomination_year].nil?
      params[:nomination_nomination_year] = Settings.current_year
    end

    @nominations = @nominations.where(
    "nominee_first_name like ? OR nominee_last_name like ? OR " + \
    "nominating_official_first_name like ? OR nominating_official_last_name like ? OR " + \
    "nominating_point_of_contact_first_name like ? OR nominating_point_of_contact_last_name like ? OR nominee_team_name like ?",
    "%#{params[:search]}%","%#{params[:search]}%",
    "%#{params[:search]}%","%#{params[:search]}%",
    "%#{params[:search]}%","%#{params[:search]}%" ,"%#{params[:search]}%") unless params[:search].blank?
    @nominations = @nominations.where("award_option_id = ?","#{params[:nomination_award_option_id]}") unless params[:nomination_award_option_id].blank?
    @nominations = @nominations.where("nomination_type_id = ?","#{params[:nomination_nomination_type_id]}") unless params[:nomination_nomination_type_id].blank?
    @nominations = @nominations.where("nomination_year = ?","#{params[:nomination_nomination_year]}") unless params[:nomination_nomination_year].blank?
    @nominations = @nominations.where(status: params[:status]) unless params[:status].blank?
    #@nominations = @nominations.where("nomination_year = ?", Settings.current_year)
    #@nominations = @nominations.page params[:page] #User.all
    @nomination_types = NominationType.all.pluck(:code,:id)
  end

  def edit
    @info = NominationType.where(["code = ?", @nomination.nomination_type.code]).first
    @info.year = @nomination.nomination_year
    @info.id = @nomination.nomination_type_id
    @nomination_type = @nomination.nomination_type.code
    @nomination_types = NominationType.all.pluck(:code,:id)
    @award_options = AwardOption.all.pluck(:name,:id)
    @callback = "#"
    @manage_nomination = true
    @remove_submission_packet = nil
  end

  def show
    @nomination = Nomination.find(params[:id])
    #depending on the nomination type, choose the appropriate controller

    @info = NominationType.where(["code = ?", @nomination.nomination_type.code]).first
    @info.year = @nomination.nomination_year
    @info.id = @nomination.nomination_type_id
    @nomination_type = @nomination.nomination_type.code
    @nomination_types = NominationType.all.pluck(:code,:id)
    @award_options = AwardOption.all.pluck(:name,:id)
    @callback = "#"
    @manage_nomination = true

    unless current_user.admin?
      unless @user == current_user
        redirect_to action: "index", :alert => "Access denied."
      end
    end
  end

  def list
    @nominations = Nomination.all
    @nomination_types = NominationType.where(["instr(award_years_list, ?)", Settings.current_year])
  end

  # PATCH/PUT /boats/1
  # PATCH/PUT /boats/1.json
  def update

    respond_to do |format|
      if @nomination.update(nomination_params)

        # if build-submission-packet is checked, then create packet
        if params[:remove_submission_packet] == "yes"

          @nomination.remove_submission_packet!
          @nomination.save

        end

        if params[:build_submission_packet] == "yes"

          #TODO
          # determine which documents to merge based on nomination type
          # for packard, should, achievement, development:  submission_form_award_narrative and endorsement_letter
          # for logistic: ???
          # for product_support: ???



          begin
            case @nomination.nomination_type.code
            when true
            else
              submission_packet_contents_base64 = CreatePDF(@nomination.submission_form_award_narrative.current_path,  @nomination.endorsement_letter.current_path)
            end
            binpdf = Base64.decode64(submission_packet_contents_base64)
            file3 = Tempfile.new(['foo','.pdf'])
            begin
              File.open(file3, "wb") do |f|
                f.write(binpdf)
              end
            ensure
               file3.close
               @nomination.submission_packet = file3
               file3.unlink   # deletes the temp file
            end
            @nomination.save!
          rescue => e
            puts e.inspect
          end

        end

        # merge all approved packets for this nomination type
        begin
          out = MergePDF(@nomination.nomination_year,@nomination.nomination_type_id)
        rescue => e
          puts e.inspect
        end

        format.html { redirect_to edit_nomination_url(@nomination), notice: 'Nomination was successfully updated.' }
        format.json { render :index, status: :ok, location: @nomination }
      else

        @info = NominationType.where(["code = ?", @nomination.nomination_type.code]).first
        @info.year = @nomination.nomination_year
        @info.id = @nomination.nomination_type_id
        @nomination_type = @nomination.nomination_type.code
        @nomination_types = NominationType.all.pluck(:code,:id)
        @award_options = AwardOption.all.pluck(:name,:id)
        @callback = "#"
        @manage_nomination = true
        @remove_submission_packet = nil
        format.html { render :edit }
        format.json { render json: @nomination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boats/1
  # DELETE /boats/1.json
  def destroy
    @nomination.destroy
    respond_to do |format|
      format.html { redirect_to nominations_url, notice: 'Nomination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def update_awards
    @award_option = params[:option_id]

    if params[:id].blank?
      @award = AwardOption.pluck(:name,:id)
    else
      @award = AwardOption.joins(:nomination_type).where("nomination_type_id  = ?", params[:id]).pluck(:name,:id)
    end
    respond_to do |format|
      format.js
    end
  end

  private

    def manager_or_admin_only
      unless current_user.admin? || current_user.manager?
        redirect_to :root, :alert => "Access denied."
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_nomination
      @nomination = Nomination.find(params[:id])
      if @nomination.nomination_type.code == "Logistic"
        @nominataion = ProductSupport.find(params[:id])
      end
    end

    def set_nomination_type
       @nomination_type = nomination_type
    end

    def nomination_type
        Nomination.nomination_types.include?(params[:type]) ? params[:type] : "Nomination"
    end

    def nomination_type_class
        nomination_type.constantize
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nomination_params
      params.require(:nomination).permit(
      :unit_commander_title,
      :unit_commander_first_name,
      :unit_commander_last_name,
      :unit_commander_suffix,
      :unit_commander_phone,
      :unit_commander_email,
      :unit_commander_organization,
      :nominating_official_title,
      :nominating_official_first_name,
      :nominating_official_last_name,
      :nominating_official_suffix,
      :nominating_official_phone,
      :nominating_official_email,
      :nominating_point_of_contact_title,
      :nominating_point_of_contact_first_name,
      :nominating_point_of_contact_last_name,
      :nominating_point_of_contact_suffix,
      :nominating_point_of_contact_phone,
      :nominating_point_of_contact_email,
      :nominating_point_of_contact_organization_address_1,
      :nominating_point_of_contact_organization_address_2,
      :nominating_point_of_contact_city,
      :nominating_point_of_contact_state,
      :nominating_point_of_contact_zip,
      :nominating_point_of_contact_country,
      :award_option_id,
      :nominee_title,
      :nominee_first_name,
      :nominee_last_name,
      :nominee_suffix,
      :nominee_position_title,
      :nominee_email,
      :nominee_organization,
      :nominee_command,
      :endorsement_letter,
      :submission_form_award_narrative,
      :nominee_organization_logo,
      :nomination_type_id,
      :nomination_year,
      :nominee_team_name,
      :submission_form_award_narrative_cache,
      :endorsement_letter_cache,
      :nominee_organization_logo_cache,
      :submission_word_document,
      :submission_pdf,
      :submission_word_document_cache,
      :submission_pdf_cache,
      :status,
      :remove_submission_packet,
      :submission_packet,
      :submission_packet_cache,
      :nominee_photograph_one,
      :nominee_photograph_one_cache,
      :nominee_photograph_two,
      :nominee_photograph_two_cache)
    end


end

app/helpers/nominations_helper.rb
module NominationsHelper
end

app/views/nominations/create.html.erb
<h1>Nominations#create</h1>
<p>Find me in app/views/nominations/create.html.erb</p>

app/views/nominations/edit.html.erb
<div class="row  white-bg page-heading">
    <div class="col-lg-8 col-lg-offset-1">
        <%= render "shared/usaasc_vb" %>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'landing', :action => 'index' %>">Home</a>
            </li>
            <li>
              <%= link_to 'Manage Nominations', :action => "index" %>
            </li>
        <li class="active">
            <strong>Manage</strong>
        </li>
        </ol>
    </div>
    <div class="col-lg-2">
    <div class="title-action">
        <%= link_to '/users/sign_out', :method => :delete do %><i class="fa fa-sign-out"></i> Signoff<% end %>
    </div>
    </div>
</div>

<div class="row page-heading">
</div>



<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <p id="notice"><%= notice %></p>
      <% if @nomination.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@nomination.errors.count, "error") %> prohibited this nomination from being saved:</h2>
          <ul>
          <% @nomination.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>
    </div>
</div>



<%= form_for @nomination, html: {class: "form-horizontal"} do |f| %>

<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Manage Nomination Options</h5>
                </br>
                <div class="help-block m-b-none">Change meta data about the Nomination</div>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                </div>
            </div>
            <div class="ibox-content">
              <div class="form-group row">
                <label class="col-sm-2 control-label">Created Date</label>
                <div class="col-sm-2">
                  <span class="form-control"><%= @nomination.created_at.strftime("%m/%d/%Y") %>
                  </span>
                </div>
              </div>
              <div class="form-group row">
                  <%= f.label :nomination_type_id, "Nomination", class: "col-sm-2 control-label" %>
                  <div class="col-sm-3">
                    <%= f.select :nomination_type_id, options_for_select(@nomination_types, @nomination.nomination_type_id), {}, {class: "form-control m-b", required: false } %>
                  </div>
                  <div class="help-block m-b-none col-sm-6">NOTE:  You can change the Nomination and Award to any combination, there is no validation at this time.</div>


              </div>
              <div class="form-group row">
                  <%= f.label :award_option_id, "Award", class: "col-sm-2 control-label" %>

                  <div class="col-sm-6">

                  <%= f.select :award_option_id, options_for_select(@award_options, @nomination.award_option_id),  {}, {class: "form-control m-b", required: true} %>


                  </div>
              </div>
              <div class="form-group row">
                  <%= f.label :status, "Status", class: "col-sm-2 control-label" %>
                  <div class="col-sm-2">
                    <%= f.select :status, options_for_select([:entered, :approved, :scored, :deleted], @nomination.status), {}, {class: "form-control m-b", required: false, onchange: "fillStatusDesc();"} %>
                  </div>
                  <div class="col-sm-6">
                    <span class="help-block m-b-none" id="status_desc"></span>
                  </div>
              </div>

              <div class="form-group row">
                  <%= f.label :build_submission_packet, "Build Submission Packet", class: "col-sm-2 control-label" %>
                  <div class="col-sm-1">
                    <%= select_tag :build_submission_packet, options_for_select([:no, :yes]), class: "form-control" %>
                  </div>
                  <div class="col-sm-6">
                    <span class="help-block m-b-none">Automatically combine the Endorsement Letter and Submission Document into a single PDF.  If there is a problem,
                    you have the option to upload the Submission Packet manually.</span>
                  </div>
              </div>

              <div class="form-group row">
                <%= f.label :submission_packet, "Upload Submission Packet", class: "col-sm-2", style: "text-align: right"%>
                <% if not @nomination.submission_packet_url.blank? %>
                <div class="col-sm-3">

                  <%= link_to "View Submission Packet", @nomination.submission_packet_url, :target => "_blank",style: "valign: middle" %>
                  <br/>
                  <%= f.check_box :remove_submission_packet %>
                  &nbsp;
                  <%= label_tag :remove_submission_packet %>

                </div>
                <% end %>
                  <div class="col-sm-4">
                    <%= f.file_field :submission_packet, class: "" %>
                    <%= f.hidden_field :submission_packet_cache %>

                  </div>
              </div>
              <% if current_user.admin? %>
              <div class="hr-line-dashed"></div>
              <div class="form-group row">
                  <div class="col-sm-12">
                      <button class="btn btn-primary" type="submit">Update Nomination</button>
                      <%= link_to "Cancel", nominations_path, :id => "open-contacts-dialog-btn",
      :class => "btn btn-white", :method => :get %>

                  </div>
              </div>
              <% end %>

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <h5>Manage Nomination Form </h5>
                <br/>
                <div class="help-block m-b-none">Change nomination form informaiton</div>
                <div class="ibox-tools">
                    <a class="collapse-link">
                        <i class="fa fa-chevron-up"></i>
                    </a>

                </div>
            </div>
            <div class="ibox-content">

              <%= render :partial => "shared/nomination_base", locals: { f: f} %>

              <% if current_user.admin? %>
              <div class="hr-line-dashed"></div>
              <div class="form-group">
                  <div class="col-sm-12">
                      <button class="btn btn-primary" type="submit">Update Nomination</button>
                      <%= link_to "Cancel", nominations_path, :id => "open-contacts-dialog-btn",
      :class => "btn btn-white", :method => :get %>

                  </div>
              </div>
              <% end %>


            </div>
        </div>
    </div>
</div>
      <% end %>

      <% content_for :javascript do %>

        <script type="text/javascript">

          $(function() {

            $.webshims.setOptions('basePath', '/webshims/1.15.10/shims/')
            $.webshims.polyfill('forms forms-ext')






          });

          function fillStatusDesc() {
            $("#status_desc").html("")
            if ($("#nomination_status").val() == "entered") {
              $("#status_desc").html("entered status description")


            }
          }


    $("select#nomination_nomination_type_id").change();





        </script>

      <% end %>

      <% if not current_user.admin? %>
        <script type="text/javascript">
        $("#edit_nomination_1 :input").attr("disabled", true);
        </script>
      <% end %>

app/views/nominations/index.html.erb
<div class="row  white-bg page-heading">
    <div class="col-lg-8 col-lg-offset-1">
        <%= render "shared/usaasc_vb" %>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'landing', :action => 'index' %>">Home</a>
            </li>
            <li class="active">
            <strong>Manage Nominations</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">
    <div class="title-action">
        <%= link_to '/users/sign_out', :method => :delete do %><i class="fa fa-sign-out"></i> Signoff<% end %>
    </div>
    </div>
</div>

<div class="row page-heading">
</div>

<div class="row">
    <div class="col-lg-10 col-lg-offset-1">
      <p id="notice"><%= notice %></p>
    </div>
</div>

<div class="row">
<div class="col-lg-10 col-lg-offset-1">
<div class="ibox float-e-margins">
<div class="ibox-title">
    <h5>Manage Nominations</h5>

</div>
<div class="ibox-content">

  <%= form_tag nominations_path, :method => 'get', :id => 'form_search' do %>
    <p>
      Year:&nbsp;<%= select_tag :nomination_nomination_year,  options_for_select(Settings.award_years.collect { |c| [ c, c ] }, params[:nomination_nomination_year]) %>
      &nbsp;&nbsp;
      Name:&nbsp;<%= text_field_tag :search, params[:search], placeholder: "Nominee/Nominator/POC", size: 65 %>
    </p>
    <p>
      Nomination Type:&nbsp;
      <%= select_tag :nomination_nomination_type_id, options_from_collection_for_select(NominationType.all.order("code"), 'id', 'code', params[:nomination_nomination_type_id]), include_blank: "All" %>
      &nbsp;&nbsp;
      Award Option:&nbsp;
      <%= select_tag :nomination_award_option_id, options_from_collection_for_select(AwardOption.all.order("name"), 'id', 'name', params[:nomination_award_option_id]), include_blank: "All" %>
    </p>
    <p>   Status:&nbsp;
      <% cnt = 0 %>
      <% @statuses.each do  |s| %>
        <label class="">
        <% if params[:status].include? "#{cnt}" %>
        <input name="status[]" class="search_status" id='status<%="#{cnt}"%>' type="checkbox"  checked="checked" value='<%="#{cnt}"%>'> <%= s %></input>
        <% else %>
        <input name="status[]" class="search_status" id='status<%="#{cnt}"%>' type="checkbox" value='<%="#{cnt}"%>'> <%= s %></input>
        <% end %>
        </label>&nbsp;
        <% cnt=cnt+1 %>
      <% end %>
    </p>
    <p>
      <%= submit_tag "Search", :name => nil %>
      &nbsp;&nbsp;
      <input value="Reset" type="button" onclick='$("#search").val("");$("#nomination_type").prop("selectedIndex",0);$("#award").prop("selectedIndex",0);$(".search_status").attr("checked",false)'/>
      <span style="float:right"><%= @nominations.count %> Nomination(s) total.&nbsp;&nbsp;</span>
    </p>
  <% end %>

<table id="dataTables" class="table table-striped table-bordered table-hover dataTables-example">
  <thead>
    <tr>
      <th>Nominee Name</th>
      <th>Organization</th>
      <th>Command</th>
      <th>Nominator POC Name</th>
      <th>POC Email</th>
      <th>Type</th>
      <th>Award</th>
      <th>Status</th>
      <th>Actions</th>
      <th>Nominee Email</th>
    </tr>
  </thead>

  <tbody>
    <% @nominations.each do |nom| %>
      <tr>
        <td>
          <% if nom.nominee_team_name.blank? %>
          <%= "#{nom.nominee_title} #{nom.nominee_first_name} #{nom.nominee_last_name} #{nom.nominee_suffix}" %>
          <% else %>
          <%= nom.nominee_team_name %>
          <% end %>
        </td>
        <td>  <%= nom.nominee_organization %></td>
        <td>  <%= nom.nominee_command %></td>
        <td><%= "#{nom.nominating_point_of_contact_title} #{nom.nominating_point_of_contact_first_name} #{nom.nominating_point_of_contact_last_name} #{nom.nominating_point_of_contact_suffix}" %>
        </td>
        <td>
          <%= nom.nominating_point_of_contact_email %>
        </td>
        <td><% begin %><%= nom.nomination_type.code %><% rescue %><% end %></td>
        <td><%= nom.award_option.name %></td>
        <td><%= nom.status %>
        <td><%= link_to 'Manage', edit_nomination_path(nom) %>
        <td><%= nom.nominee_email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div   class="dataTables_info" role="status" aria-live="polite">
</div>
</div>
</div>
</div>
</div>

<% content_for :javascript do %>

<script type="text/javascript">


$(function() {

    colcnt = $("#colcnt").val()  || 0;
    //alert(colcnt);
    var table = $('#dataTables').DataTable({
        dom: 'Bfrtip',
        searching: false,
        pagingType: "full",
        //paging: true,
        pageLength: 10,
        order:  [[ colcnt, 'desc' ], [ 0, 'asc' ]],
        //pageLength: 1000,
        "columnDefs": [
            {
                "targets": [ 9 ],
                "visible": false,
                "searchable": false
            }],
        buttons: [
            //{ extend: 'copy'},
            {extend: 'csv',
             exportOptions: {
                    columns: [ 0, 1, 2, 3,4,5,6,7,9 ]
                }
            },
            {extend: 'excel', title: 'USAASC Virtual Board Nominations',
            exportOptions: {
                    columns: [ 0, 1, 2, 3,4,5,6,7,9 ]
                }
            },
            //{extend: 'pdf', title: 'ExampleFile'},

            {extend: 'pdf',
            orientation: 'landscape',
            exportOptions: {
                    columns: [ 0, 1, 2, 3,4,5,6,7,9 ]
                },

            }
        ]

    });

    $("select#nomination_nomination_type_id").change();

    var info = table.page.info();



    // set award option
  //  index = $("#nomination_award_option_id").val();
    //alert(index);
  //  $('select>option:eq(3)').prop('selected', true);
  //  $("#nomination_award_option_id option[value=" + index +"]").prop("selected",true);
  //  $("#nomination_award_option_id").blur();


});

</script>

<% end %>